name = "mocktwitter"
main = "_worker.js"
compatibility_date = "2025-09-07"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]

[[d1_databases]]
binding = "DB"
database_name = "chatdb"
database_id = "e241015f-8ee4-4c05-aebe-a39269ea513c"
