name: DO migration
on: workflow_dispatch
jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      WRANGLER_LOG: debug
    steps:
      - uses: actions/checkout@v4
      - name: Verify files
        run: |
          pwd
          ls -la
          test -f wrangler.toml || (echo "wrangler.toml missing" && exit 1)
          test -f _worker.js || (echo "_worker.js missing" && exit 1)
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            wrangler --version
            wrangler whoami
            wrangler migrations list
            wrangler migrations apply
