name: DO migration
on: workflow_dispatch
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.N6MYLgu9Ylm0ZrFVn-qyAU_M5tjxCOa6E3HPM6gI }}
          accountId: ${{ secrets.f1eb2c88041949b813f789ee8cb9caa9 }}
          command: npx wrangler migrations apply
