name: DO migration
on: workflow_dispatch
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.0bxL_UNjQzVo_IEqJvObdfpcKAwRNyo-P0JCp90I }}
          accountId: ${{ secrets.f1eb2c88041949b813f789ee8cb9caa9 }}
          command: npx wrangler migrations apply
